name: Python package
on:
  push:
    branches:
      - main
jobs:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: test
      run: echo 'Hello'